package uz.clinic

enum class UserRole {
    DEV,PATIENT,DOCTOR,DIRECTOR,CASHIER,LABORATORY
}
enum class PaymentMethod {
    CASH,CARD
}
enum class AppointmentStatus {
    PENDING,COMPLETED,CANCELLED
}enum class ResultName{
    DIAGNOSIS,ANALYSIS
}
enum class ShowPayFor{
    DOCTOR,SERVICES
}

enum class ErrorCode(val code: Int) {
    USER_NOT_FOUND(1),
    USERNAME_ALREADY_EXISTS(2),
    USERNAME_INVALID(3),
    EMPLOYEE_ALREADY_EXISTS(11),
    EMPLOYEE_NOT_FOUND(12),
    EMPLOYEE_CREATE_DONT_ENOUGH_FIELD(13),
    CLINIC_ALREADY_EXISTS(21),
    CLINIC_NOT_FOUND(22),
    DEPARTMENT_ALREADY_EXISTS(31),
    DEPARTMENT_NOT_FOUND(32),
    SERVICE_NOT_FOUND(40),
    SERVICE_ALREADY_EXISTS(41),
    SCHEDULE_ALREADY_EXISTS(50),
    SCHEDULE_NOT_FOUND(51),
    SCHEDULE_DONT_CORRECT(52),
    SCHEDULE_ALREADY_APPOINTMENTS(53),
    APPOINTMENT_NOT_FOUND(60),
    APPOINTMENT_ALREADY_EXISTS(61),
    APPOINTMENT_DONT_FIT_TO_SCHEDULE(63),
    TRANSACTION_NOT_FOUND(70),
    TRANSACTION_ALREADY_EXISTS(71),
    DIAGNOSIS_ANALYSIS_ALREADY_EXISTS(80),
    DIAGNOSIS_ANALYSIS_NOT_FOUND(81),

}